version: '3.3'
services:
    grott:
        network_mode: host
        container_name: grott
        restart: always
        environment:
            - gblockcmd=False 
            - gnomqtt=False
            - gmqttip=localhost
            - gmqttauth=False
            - gmqttuser=growatt
            - gmqttpassword=growatt2020
            - gpvoutput=False
            - gpvapikey=yourapikey 
            - gpvinverterid1=inverter1
            - gpvsystemid1=12345
            - TZ=Europe/Amsterdam 
        image: ledidobe/grott